# The Code Inspector GitHub action allows you to check if your code meets quality criteria.
# When a commit is triggered, Code Inspector checks the quality of the source code according to your own metrics threshold.

name: Code Inspector

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  check-quality:
    runs-on: ubuntu-latest
    name: A job to check my code quality
    steps:
    - name: Check code meets quality standards
      id: code-inspector
      uses: codeinspectorio/github-action@master
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        code_inspector_api_token: ${{ secrets.CODE_INSPECTOR_API_TOKEN }}
        min_quality_grade: 'WARNING'
        min_quality_score: '50'
        max_defects_rate: '0.1' 
        max_complex_functions_rate: '0.1'
        max_long_functions_rate: '0.1'
        project_name: 'ASAP project'
        max_timeout_sec: '600'
